function translate(ir, target = 'javascript') {
    const t = target.toLowerCase()
    if (t === 'javascript' || t === 'js')  return translateJS(ir)
    if (t === 'python'     || t === 'py')  return translatePython(ir)
    throw new Error(`Unknown target '${target}'. Use 'javascript' or 'python'.`)
}

function translateJS(ir) {
    const lines = [
        '// Generated by Nord Language Platform',
        '// Do not edit manually — re-run Nord to regenerate',
        ''
    ]
    for (const node of ir.nodes) {
        const code = jsStmt(node, 0)
        if (code) lines.push(code)
    }
    return lines.join('\n')
}

function ind(depth) { return '  '.repeat(depth) }

function jsStmt(node, depth) {
    if (!node) return ''
    const i = ind(depth)

    switch (node.kind) {

        case 'print':
            return `${i}console.log(${jsExpr(node.value)});`

        case 'var_decl':
            return `${i}let ${node.name} = ${jsExpr(node.value)};`

        case 'var_assign':
            return `${i}${node.name} = ${jsExpr(node.value)};`

        case 'func_decl': {
            const params = node.params.join(', ')
            const body   = node.body.map(n => jsStmt(n, depth + 1)).filter(Boolean).join('\n')
            return `${i}function ${node.name}(${params}) {\n${body}\n${i}}`
        }

        case 'return':
            return `${i}return ${jsExpr(node.value)};`

        case 'if': {
            let code = `${i}if (${jsExpr(node.condition)}) {\n`
            code    += node.consequent.map(n => jsStmt(n, depth + 1)).filter(Boolean).join('\n')
            code    += `\n${i}}`
            if (node.alternate && node.alternate.length > 0) {
                code += ` else {\n`
                code += node.alternate.map(n => jsStmt(n, depth + 1)).filter(Boolean).join('\n')
                code += `\n${i}}`
            }
            return code
        }

        case 'while': {
            const body = node.body.map(n => jsStmt(n, depth + 1)).filter(Boolean).join('\n')
            return `${i}while (${jsExpr(node.condition)}) {\n${body}\n${i}}`
        }

        case 'repeat': {
            const body = node.body.map(n => jsStmt(n, depth + 1)).filter(Boolean).join('\n')
            return `${i}for (let _i = 0; _i < ${jsExpr(node.count)}; _i++) {\n${body}\n${i}}`
        }

        case 'expr':
            return `${i}${jsExpr(node.expression)};`

        default:
            return `${i}/* unknown node: ${node.kind} */`
    }
}

function jsExpr(node) {
    if (!node) return 'undefined'

    switch (node.kind) {

        case 'literal': {
            if (node.dataType === 'string')  return JSON.stringify(node.value)
            if (node.dataType === 'boolean') return String(node.value)
            return String(node.value)
        }

        case 'identifier':
            return node.name

        case 'binary':
            return `(${jsExpr(node.left)} ${node.operator} ${jsExpr(node.right)})`

        case 'unary':
            return `${node.operator}${jsExpr(node.value)}`

        case 'call': {
            const args = (node.args || []).map(jsExpr).join(', ')
            return `${node.callee}(${args})`
        }

        case 'input': {
            const promptStr = node.prompt ? JSON.stringify(node.prompt + ' ') : '""'
            return `_input(${promptStr})`
        }

        default:
            return 'null'
    }
}

function translatePython(ir) {
    const lines = [
        '# Generated by Nord Language Platform',
        '# Do not edit manually — re-run Nord to regenerate',
        ''
    ]
    for (const node of ir.nodes) {
        const code = pyStmt(node, 0)
        if (code) lines.push(code)
    }
    return lines.join('\n')
}

function pyInd(depth) { return '    '.repeat(depth) }

function pyStmt(node, depth) {
    if (!node) return ''
    const i = pyInd(depth)

    switch (node.kind) {

        case 'print':
            return `${i}print(${pyExpr(node.value)})`

        case 'var_decl':
        case 'var_assign':
            return `${i}${node.name} = ${pyExpr(node.value)}`

        case 'func_decl': {
            const params = node.params.join(', ')
            const rawBody = node.body.map(n => pyStmt(n, depth + 1)).filter(Boolean)
            const body = rawBody.length > 0 ? rawBody.join('\n') : `${i}    pass`
            return `${i}def ${node.name}(${params}):\n${body}`
        }

        case 'return':
            return `${i}return ${pyExpr(node.value)}`

        case 'if': {
            const rawCons = node.consequent.map(n => pyStmt(n, depth + 1)).filter(Boolean)
            const cons = rawCons.length > 0 ? rawCons.join('\n') : `${i}    pass`
            let code = `${i}if ${pyExpr(node.condition)}:\n${cons}`
            if (node.alternate && node.alternate.length > 0) {
                const rawAlt = node.alternate.map(n => pyStmt(n, depth + 1)).filter(Boolean)
                const alt = rawAlt.length > 0 ? rawAlt.join('\n') : `${i}    pass`
                code += `\n${i}else:\n${alt}`
            }
            return code
        }

        case 'while': {
            const rawBody = node.body.map(n => pyStmt(n, depth + 1)).filter(Boolean)
            const body = rawBody.length > 0 ? rawBody.join('\n') : `${i}    pass`
            return `${i}while ${pyExpr(node.condition)}:\n${body}`
        }

        case 'repeat': {
            const rawBody = node.body.map(n => pyStmt(n, depth + 1)).filter(Boolean)
            const body = rawBody.length > 0 ? rawBody.join('\n') : `${i}    pass`
            return `${i}for _i in range(${pyExpr(node.count)}):\n${body}`
        }

        case 'expr':
            return `${i}${pyExpr(node.expression)}`

        default:
            return `${i}# unknown node: ${node.kind}`
    }
}

function pyExpr(node) {
    if (!node) return 'None'

    switch (node.kind) {

        case 'literal': {
            if (node.dataType === 'string')  return JSON.stringify(node.value)
            if (node.dataType === 'boolean') return node.value ? 'True' : 'False'
            return String(node.value)
        }

        case 'identifier':
            return node.name

        case 'binary': {
            let op = node.operator
            if (op === '&&') op = 'and'
            if (op === '||') op = 'or'
            return `(${pyExpr(node.left)} ${op} ${pyExpr(node.right)})`
        }

        case 'unary': {
            const op = node.operator === '!' ? 'not ' : node.operator
            return `${op}${pyExpr(node.value)}`
        }

        case 'call': {
            const args = (node.args || []).map(pyExpr).join(', ')
            return `${node.callee}(${args})`
        }

        case 'input': {
            const prompt = node.prompt ? JSON.stringify(node.prompt + ' ') : '""'
            return `input(${prompt})`
        }

        default:
            return 'None'
    }
}

module.exports = { translate, translateJS, translatePython }